### ISSUE TITLE
Angular2 version of pulltorefresh

### ISSUE THREAD

**Issue by yeulucay** [bradmartin/nativescript-pulltorefresh#11]
I want to add your component to my {N} Angular app.

and added this in my component ts file. 

```
import { registerElement, ViewClass } from "nativescript-angular/element-registry";

registerElement("PullToRefresh", () => {
    var viewClass = require("nativescript-pulltorefresh").PullToRefresh;
    return viewClass;
});
```

in the view page used it like that

```
   <pullToRefresh>
        <ListView [items]="groceryList" row="2" class="small-spacing" [class.visible]="listLoaded">
            <template let-item="item">
                <Label [text]="item.name" class="medium-spacing"></Label>
            </template>
        </ListView>
    </pullToRefresh>
```

It works and refresh spinner is shown on the top of the list when you pull down. But it should somehow trigger a method. lets suppose method name is 

`refreshList(){}`

how will I use it from the view?

**Comment by bradmartin** [comment]
There is a refresh event on the component. I'm not sure about ng2 as I
don't use it yet but it does work as I've seen people using it on the slack
channel. So I'm guessing just add the refresh event, look at the sample on
the README

**Comment by leocaseiro** [comment]
You just need to call the refresh event:

```html
    <PullToRefresh (refresh)="refreshList($event)" >
        <ListView [items]="groceryList" row="2" class="small-spacing" [class.visible]="listLoaded">
            <template let-item="item">
                <Label [text]="item.name" class="medium-spacing"></Label>
            </template>
        </ListView>
    </PullToRefresh>
````

**Comment by bradmartin** [comment]
Closing @yeulucay - if you need help using this see above comment.
