### ISSUE TITLE
Typescript Error While Registering PullToRefresh In NG2 App

### ISSUE THREAD

**Issue by shripalsoni04** [bradmartin/nativescript-pulltorefresh#13]
To use PullToRefresh in angular 2 app, when we try to register PullToRefresh by `registerElement('PullToRefresh', () => PullToRefresh);`. Typescript compiler gives error: '() => typeof PullToRefresh' is not assignable to parameter of type '() => ViewClass'.

The error is due to in definition file, extending PullToRefresh by ContentView is missing.

So extending PullToRefresh by ContentView in definition file will fix this.
```
import { ContentView } from 'ui/content-view';

export declare class PullToRefresh extends ContentView {
...
}
```

**Comment by bradmartin** [comment]
Fixed: https://www.npmjs.com/package/nativescript-pulltorefresh
