### ISSUE TITLE
Question: Using in NS angular project

### ISSUE THREAD

**Issue by devna13** [bradmartin/nativescript-pulltorefresh#14]
Tried this layout in NS angular project and it didn't work.

```
<ScrollView>
<StackLayout>
<PullToRefresh refresh="load()">
... 
</PullToRefresh>
</StackLayout>
</ScrollView>
```

Is there any declaration in NgModule required to use this plugin ?

Thanks

**Comment by bradmartin** [comment]
Possibly, don't use ng2 myself but see here for another component: https://github.com/bradmartin/nativescript-drawingpad#angular

**Comment by devna13** [comment]
Thanks @bradmartin. Tried different codes and this worked. 

```
import {registerElement} from "nativescript-angular/element-registry";
registerElement("PullToRefresh", () => require("nativescript-pulltorefresh").PullToRefresh);
```

```
<PullToRefresh (refresh)="load()" #pullToRefresh> 
</PullToRefresh>
```
