### ISSUE TITLE
Not working in TNS 2.5

### ISSUE THREAD

**Issue by elvismercado** [bradmartin/nativescript-pulltorefresh#18]
`file:///app/tns_modules/nativescript-pulltorefresh/pulltorefresh.js:65:71: JS ERROR Error: Content must inherit from UIScrollView!
`

**Comment by bradmartin** [comment]
That's a layout issue. Can you provide your UI markup?

**Comment by elvismercado** [comment]
Essentially the same example on the github page is within the schedules directive

```
<GridLayout>
	<TabView #tabView class="tab-view" [selectedIndex]="tabindex" (selectedIndexChanged)="onSelectedIndexChanged(tabView.selectedIndex)">
		<GridLayout *tabItem="{title: 'Planning'}">
			<schedules></schedules>
		</GridLayout>
	</TabView>
</GridLayout>
```

**Comment by bradmartin** [comment]
Is the refresh inside the schedules?

**Comment by elvismercado** [comment]
yes, this is the view of the schedules

```
<stack-layout>   
        <PullRefresh refresh="refresh()">
        	<GridLayout>
				<ListView>
				</ListView>
			</GridLayout>
        </PullRefresh>
</stack-layout>


	refresh() {
		alert("Hello World!")
	}
```

**Comment by elvismercado** [comment]
@bradmartin I got the view to work. Problem was the gridlayout between the pulltorefresh and listview directive

But, i cannot get the refresh event to work

**Comment by bradmartin** [comment]
Also you have a grid-stack-schedules which doesn't seem necessary at quick glance. That might be causing an issue. I forget the specifics with the layouts on iOS and making this work. I've encountered it before and just tweaking the layout resolves the issue. I just never know what it is exactly :) I don't do a lot of iOS so I just get it working and move on. I'll ping Peter later or you can on the issue and see if he has any thoughts from your code.

**Comment by elvismercado** [comment]
Yes right. The listview needs to be a direct child of PullToRefresh I got the correct syntax now for angular2. Maybe you should include this in your readme for angular2

```
main.ts
import {registerElement} from "nativescript-angular/element-registry";
registerElement("PullToRefresh", () => require("nativescript-pulltorefresh").PullToRefresh);
```

```
component.html
<PullToRefresh (refresh)="refresh($event)">
    <ListView>
    </ListView
</PullToRefresh>
```

```
component.ts
refresh(args) {
    let pullRefresh = args.object;
    alert("Hello World!");
    pullRefresh.refreshing = false;
}
```

**Comment by bradmartin** [comment]
So it's working now, if so I can add it to the README or if you want to submit a PR with that below the plain NS sample that would be great 😄

**Comment by elvismercado** [comment]
I think an example in the readme is ok. If i ever get to check dive deeper in the code i'll create a PR

**Comment by hasbyalkaff** [comment]
hello, help me,  i got same issue with this. Im use pulltorefresh, to get data from db and check them for current data.. not for listview..

this work perfectly for Android, but not for IOS. 😢 

Here my code:

my UI.xml
`<page navigatedTo="onNavigatedTo"
    xmlns:PR="nativescript-pulltorefresh">

    <ActionBar title="RAN1" class="action-bar">
    </ActionBar>

    <PR:PullToRefresh refresh="onRefresh">    
        <grid-layout rows="auto,*" columns="*">
            <stack-layout col="0" row="0" class="ads" >
                <label class="tanya" text="{{ question }}" textWrap="true" />
            </stack-layout>

            <stack-layout col="0" row="1" class="content" visibility="{{ showForm ? 'visible' : 'collapsed' }}">
                <label class="label" text="Your Answer :" />
                <grid-layout rows="auto, auto" columns="*, *" visibility="{{ showEssay ? 'visible' : 'collapsed' }}">
                    <text-field row="0" colSpan="2" id="answer" />
                    <button row="1" col="1" text="Lock" tap="onLock" horizontalAlignment="right" />
                </grid-layout>

                <grid-layout rows="auto" columns="*, *" visibility="{{ showOption ? 'visible' : 'collapsed' }}">
                    <button row="0" col="0" tap="onTapA" text="{{ option_a }}" />
                    <button row="0" col="1" tap="onTapB" text="{{ option_b }}" />
                </grid-layout>
            </stack-layout>
        </grid-layout>
    </PR:PullToRefresh>
</page>`

my controller.js
`function onRefresh(args){
    var pullRefresh = args.object;
    statusChecker.start().then(function(bool){
        pullRefresh.refreshing = false;
        if(bool){
            condition = statusChecker.getStatusClass();
            setQuestion();
        }
        else alert("Failed. Check your connection!");
    });
}`
