### ISSUE TITLE
Cannot scroll ListView up

### ISSUE THREAD

**Issue by mvdklip** [bradmartin/nativescript-pulltorefresh#19]
Not sure if this is intentional but I have setup a ListView with some images and labels inside an Android app. Without PullToRefresh I can scroll up and down the list. After adding the PullToRefresh however I can only scroll down. Scrolling up immediately triggers a refresh gesture. Instead I expected to be able to scroll all the way up to the top of the ListView before the refresh gesture kicks in.

**Comment by mvdklip** [comment]
Never mind, had a TabView in between. Rearranged the order of components and now it works as aspected. The ListView needs to be directly under the PullToRefresh. Maybe worth documenting as the "on any view" phrase seems not entirely true?

**Comment by bradmartin** [comment]
For sure. Prob rephrase that to explain it extends ContentView so it's just
a layout container like stack layout, grid, etc. I'll try to circle back to
that later. Thanks
