### ISSUE TITLE
Request: Update for Nativescript 3.0 Breaking Changes

### ISSUE THREAD

**Issue by bbetter** [bradmartin/nativescript-pulltorefresh#22]
fix issue with ui/proxy which is now not available

**Comment by JPM84** [comment]
This is the error in 3.0RC:
```TypeError: Could not load view for: PullToRefresh.Error: Could not find module 'ui/core/proxy'.```

**Comment by bradmartin** [comment]
https://www.npmjs.com/package/nativescript-pulltorefresh - thanks @PeterStaev
