### ISSUE TITLE
Crashes app on android.

### ISSUE THREAD

**Issue by davecoffin** [bradmartin/nativescript-pulltorefresh#24]
I created this repo (a bare hello world template) to demonstrate this bug:
https://github.com/davecoffin/PullToRefresh-Android-Bug

In a nutshell though:
```
// main-page.xml
<Page xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:PullRefresh="nativescript-pulltorefresh"  navigatingTo="onNavigatingTo" class="page">
    <Page.actionBar>
        <ActionBar title="My App" icon="" class="action-bar">
        </ActionBar>
    </Page.actionBar>
    <GridLayout>
        <PullRefresh:PullToRefresh refresh="refresh">
            <ScrollView>
                <Label text="sup" />
            </ScrollView>
        </PullRefresh:PullToRefresh>
    </GridLayout>
</Page>
```

```
// main-page.js
var createViewModel = require("./main-view-model").createViewModel;
function onNavigatingTo(args) {
    var page = args.object;
    page.bindingContext = createViewModel();
}
exports.refresh = function(args) {
    console.log('done');
}
exports.onNavigatingTo = onNavigatingTo;
```

and the error is:

```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to resume activity {org.nativescript.AndroidTest/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreateView failed

Error: java.lang.NullPointerException
    android.widget.TextView.setTextColor(TextView.java:3260)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
    com.tns.Runtime.callJSMethod(Runtime.java:1047)
    com.tns.Runtime.callJSMethod(Runtime.java:1028)
    com.tns.Runtime.callJSMethod(Runtime.java:1018)
    com.tns.FragmentClass.onCreateView(android.app.Fragment.java)
    android.app.Fragment.performCreateView(Fragment.java:2352)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
    android.app.BackStackRecord.run(BackStackRecord.java:815)
    android.app.F
```

**Comment by davecoffin** [comment]
@bradmartin do you agree that this can and should be fixed in the pulltorefresh plugin?

**Comment by bradmartin** [comment]
Possibly, I'm just not sure right now what the plugin would be doing that would cause it 🤔 if we know what the cause is then fixing here is great. I'm just not sure without more debugging on the issue and limited on time right now :(

**Comment by bradmartin** [comment]
@PeterStaev helped with updating the plugin and he might be a little 'fresh' on the specifics of the plugin having recently worked on it. Peter, do you have any idea what would cause the PullToRefresh layout to cause this issue?

**Comment by PeterStaev** [comment]
My guess is this might relate to https://github.com/bradmartin/nativescript-pulltorefresh/blob/master/pulltorefresh-common.ts#L14, where we remember the initial value and then change it back. This was done as far as i remember because when you set the color property of the widget it also changed the color of all the content inside it.

**Comment by PeterStaev** [comment]
I've just did a quick test, and good news is this problem is not present in 2.0.0 version of the plugin and the core 3.0 modules. So my guess is it was a mix of some problem with the 2.5 core modules and how the plugin is implemented. 

@davecoffin I would suggest using the workaround that @bradmartin suggested - to define a color property for the label, and then when you upgrade your project to {N} 3.0 to remove that color.

**Comment by bradmartin** [comment]
@davecoffin is this better as Peter suggested with 3+? I'm about to implement it in an app so I'll report back if any issue related to this.

**Comment by davecoffin** [comment]
@bradmartin I'm not ignoring you, I went to test this yesterday morning which sent me on a wild goose chase fixing android build bugs that I still havent resolved.

**Comment by davecoffin** [comment]
This is crazy, but this bug has resurfaced. It happens for me in 3.4.1.

**Comment by felix-idf** [comment]
@davecoffin @bradmartin 
I also get this error using NS 5.2 and the latest version of this plugin.

Surprisingly the error does not occur if I add a color to the Label.

<Label text="Test"/>  --> crash
<Label text="Test" color="black"/> --> no crash
