### ISSUE TITLE
Need to use it with tns version 2.5.0

### ISSUE THREAD

**Issue by ryanzaatari** [bradmartin/nativescript-pulltorefresh#25]
What version of the plugin should I add with tns version 2.5.0 ?

**Comment by bradmartin** [comment]
Try installing 1.1.10 - I think that was the last release prior to supporting NS 3.0. I forgot to document the versions on the readme :) will do that later. Thanks.

**Comment by ryanzaatari** [comment]
Yes @bradmartin , version 1.1.10 worked perfectly.

cheers!
