### ISSUE TITLE
Incompatible with swipe gestures

### ISSUE THREAD

**Issue by sittingbool** [bradmartin/nativescript-pulltorefresh#29]
Hi I am using wipe gestures (left / right) from [this slides plugin](https://github.com/TheOriginalJosh/nativescript-ngx-slides) and they don't work anymore when i put this plugin around the content. tested it on android. NS version 3.1.1, using Angular.

**Comment by kalininskiy** [comment]
I have same problem with "nativescript-carouse"l - left/right swipe conflict with nativescript-pulltorefresh vertical swipe
but this problem only with Android, in iOS work fine and no swipe conflicts

**Comment by TheOnlyMatt** [comment]
Hi,
@kalininskiy @sittingbool Did you find a way to solve this ?
I have exactly the same problem with the carousel and pull refresh conflicting

**Comment by sittingbool** [comment]
Nope, I can think of the reason: the gesture is taken by the upper view and not forwarded through the view stack anymore. But since at least one module is entirely written in Angular and the gesture is recognized in the native code I guess the changes have to be made in NativeScript itself. I ended up with just using one of these modules per screen. But I know that in iOS  as well as in Android you can implement native code to handle double gestures. I just didn't make it that far because my ability to write plugins in NS (which is required to access native code) is to limited. But I'm learning.

**Comment by TheOnlyMatt** [comment]
Ok, thank you for your quick answer, I will try to bypass the problem by disabling the slide gesture on Android and replace it by prev/next arrows.
Perhaps that I will try later to find a fix to get it working.

**Comment by CodeCoded** [comment]
Hi

I was wondering if anyone has solved this or come up with a good alternative? 

Thanks
