### ISSUE TITLE
Not working on Latest NativeScript

### ISSUE THREAD

**Issue by chrisbellman** [bradmartin/nativescript-pulltorefresh#30]
Using NativeScript + Angular. Am I missing something?

CONSOLE ERROR file:///app/tns_modules/@angular/core/./bundles/core.umd.js:1091:24: ERROR Error: Uncaught (in promise): Error: Content must inherit from UIScrollView!

```
<FlexboxLayout>
<PullToRefresh (refresh)="refreshList($event)">
  <ListView *ngIf="feed || followFeed"
            [items]="cacheKey === 'main' ? recentFeed[filterMap['']] : followFeed[filterMap['']]"
            class="list-group"
            (loadMoreItems)="onScrollDown()">
    <ng-template let-item="item">
      <feed-card></feed-card>
    </ng-template>
  </ListView>
</PullToRefresh>
</FlexboxLayout>
```

```
import { registerElement } from 'nativescript-angular/element-registry';
registerElement('PullToRefresh', () => require('nativescript-pulltorefresh').PullToRefresh);

  public refreshList(args) {
    var pullRefresh = args.object;
    this.updateFeed();
    setTimeout(function () {
      pullRefresh.refreshing = false;
    }, 1000);
  }
```

**Comment by bradmartin** [comment]
Hi @chrisbellman - on iOS the layout has certain requirements and the error indicates it. I'm not the best iOS dev around so I don't claim to know much there 😄 but basically your layout needs some tweaks to get it working. Could you try switching out the `flexboxlayout` with a `stacklayout` and see if the same issue persists. If so, then try a `stacklayout` inside the pulltorefresh that will wrap the listview. One of those two should help get it working. Keep me posted.

**Comment by chrisbellman** [comment]
If I put a StackLayout outside or inside the PullToRefresh before the ListView, I get this error:
CONSOLE ERROR file:///app/tns_modules/@angular/core/./bundles/core.umd.js:1091:24: ERROR Error: Uncaught (in promise): Error: Content must inherit from UIScrollView!

**Comment by bradmartin** [comment]
Maybe it's the `ng-template` I haven't used it in an NG app but I know it worked at one time just fine 😕 keep me posted if you find anything.

**Comment by bradmartin** [comment]
@chrisbellman did you figure this out? The plain NS demo is working fine on latest. I haven't tried it within angular, let me know and we can reopen if needed.
