### ISSUE TITLE
Layout issue with NativeScript 3.2

### ISSUE THREAD

**Issue by iShankarG** [bradmartin/nativescript-pulltorefresh#32]
Layout not working when `PullToRefresh` used, below is my code

    <GridLayout xmlns="http://schemas.nativescript.org/tns.xsd"
	    xmlns:PullRefresh="nativescript-pulltorefresh" class="page-content" loaded="onLoaded">
	    <PullRefresh:PullToRefresh refresh="refreshList">
	    	<Label class="page-icon fa" text="&#xf015;"></Label>
	    	<Label class="page-placeholder" color="#000" text="Lorem ipsum irure ex ad ut ad cillum veniam in ea tempor nulla ad dolore consectetur dolore est ut cillum dolore irure aliqua in."></Label>
	    </PullRefresh:PullToRefresh>
	</GridLayout>

# Expected: 
![screenshot_2017-09-14-20-45-45](https://user-images.githubusercontent.com/4340118/30440386-fd8283b8-9993-11e7-8337-e603d7183295.jpeg)

# What I got:
![screenshot_2017-09-14-20-48-31](https://user-images.githubusercontent.com/4340118/30440404-0b51416e-9994-11e7-80d8-940ccaacb1bc.jpeg)

When `PullRefresh:PullToRefresh` is commented everything works fine.

**Comment by bradmartin** [comment]
The `PullToRefresh` is a layout similar to StackLayout or other content-view views. Try setting a height of 100% and width of 100% on it so that it fills the page. That should help some.

**Comment by iShankarG** [comment]
@bradmartin It's working and Thank's for your plugin.
