### ISSUE TITLE
Webpack android build fails with uglify

### ISSUE THREAD

**Issue by manojdcoder** [bradmartin/nativescript-pulltorefresh#33]
Without adding [SewipeRefreshListener](https://github.com/bradmartin/nativescript-pulltorefresh/blob/master/pulltorefresh.android.ts#L70) to mangle, android build fails when using uglify. Please add the instructions to read me.

**Comment by bradmartin** [comment]
Do you care to submit a PR with the instructions? :)

**Comment by jogboms** [comment]
@manojdcoder can you describe?

**Comment by manojdcoder** [comment]
@bradmartin Please merge #34, added instructions to ReadMe.
