### ISSUE TITLE
refreshing = false does not work on empty ListView

### ISSUE THREAD

**Issue by svanegaard** [bradmartin/nativescript-pulltorefresh#39]
Spinner does not disappear when setting "refreshing" to false on an empty ListView.

**Comment by svanegaard** [comment]
The issue was related to another problem and not an issue with this plugin!

**Comment by mathieutu** [comment]
@svanegaard Hi, I've the same problem (with a not empty ListView), how did you manage it?

**Comment by eloiqs** [comment]
Hi, I'm having the same issue but with a ScrollView inside the PullToRefresh component instead of an empty ListView.
