### ISSUE TITLE
How to register element properly?

### ISSUE THREAD

**Issue by jiro412j** [bradmartin/nativescript-pulltorefresh#41]
I try to import

`import { registerElement } from "nativescript-angular/element-registry";
registerElement("PullToRefresh", () => require("nativescript-pulltorefresh").PullToRefresh);`

 inside `component.ts`. I got this error everytime. 
`ERROR Error: Content must inherit from either UIScrollView, UIWebView or WKWebView!`

<img width="1186" alt="1__tns_run_ios_--emulator__simctl_" src="https://user-images.githubusercontent.com/14954947/36537237-206c44d0-1802-11e8-8d69-563b7598c8fb.png">

**Comment by bradmartin** [comment]
Can you post your markup, that is where your issue is with that error. Thanks :)
