### ISSUE TITLE
nativescript-vue

### ISSUE THREAD

**Issue by jeremiasjutz** [bradmartin/nativescript-pulltorefresh#42]
How can I make it work with nativescript-vue?

So far I have put this at the top of my file:
```javascript
const PullToRefresh = require('nativescript-pulltorefresh');
Vue.registerElement('PullToRefresh', () => require('nativescript-pulltorefresh').PullToRefresh);
```

and then I have a stacklayout between the PullToRefresh Tags.
`<Page xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:PullRefresh="nativescript-pulltorefresh">`  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<PullRefresh:PullToRefresh refresh="refreshList">` 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<StackLayout>...</StackLayout>` 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<PullRefresh:PullToRefresh />` 
`</Page>`

**Comment by strebl** [comment]
Maybe you found the solution already, but that works:
```
<PullToRefresh @refresh="refreshList">
  <StackLayout>...</StackLayout>
</PullToRefresh>
```

**Comment by kuamatzin** [comment]
@strebl in what file did you put:

Vue.registerElement('PullToRefresh', () => require('nativescript-pulltorefresh').PullToRefresh);

**Comment by strebl** [comment]
@kuamatzin I added it to the file `main.js`.
