### ISSUE TITLE
Can't find UIRefreshControl in pulltorefresh.d.ts

### ISSUE THREAD

**Issue by ngydat** [bradmartin/nativescript-pulltorefresh#5]
Hello @bradmartin 

I'm contacting you again because I have this little error in the file I mentioned in the title.
I know UIRefreshControl is a class used in iOS but in the file, the compiler can't seem to recognize it. Do I need a require somewhere ?

Thank you again

**Comment by bradmartin** [comment]
No you don't *need* it but if you want to silence the compiler you could add a local variable to silence the warnings. Something like `var UIRefreshControl = UIRefreshControl;` then the compiler would quit complaining. Or you can just ignore it and know that the native class is available and just not defined in the module. I might ping Peter to get his thoughts on the best approach to silence the compiler for native classes.

**Comment by matt4446** [comment]
I've decided to hide all my typescript errors away today, which was fun. 

@ngydat this is how I've solved that issue:
[ios.dummy.d.ts](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/master/typings/ios.dummy.d.ts#L13)  
^
don't forget to reference the file.  

@bradmartin I added a pull request for the two other (one really) typescript errors which @ngydat was stuck on over here: https://github.com/NativeScript/nativescript-angular/issues/157

**Comment by bradmartin** [comment]
Merged the PR, all should be good here. Any issues let me know 👍
