### ISSUE TITLE
NPM "nativescript-pulltorefresh": "1.1.3" is missing the typescript definitions. 

### ISSUE THREAD

**Issue by matt4446** [bradmartin/nativescript-pulltorefresh#7]
1.1.2 seems ok though.

**Comment by bradmartin** [comment]
Ah man I totally excluded all TS files by accident from npm. :scream: I'll
fix this later. Thanks for pointing that out.

**Comment by matt4446** [comment]
No problem ... my code has been stuck (unable to run) for a few days so I will look for the update soon ;-)

**Comment by bradmartin** [comment]
Fixed.
