### ISSUE TITLE
Pan Event Question - is it bubbled up?

### ISSUE THREAD

**Issue by matt4446** [bradmartin/nativescript-pulltorefresh#9]
I'm not certain how the events get bubbled in NativeScript or NativeScript-Angular so may not be your problem ;-) 

I have the pull to refresh on most of my pages but if I show the most irrelevant one (feels quite hypnotic):
![refresh-pointless-page](https://cloud.githubusercontent.com/assets/1550939/15487512/bdad6400-2145-11e6-99f6-e81adfbd10e4.gif)

On the `stackpanel` behind the `pull-to-refresh` I'm looking for the pan events as I want to make the aside left or aside right show depending if the user drags over a threshold left or right.

Panning on the element above (nav) I can get the events (nav is still a child of center content in this case like the pull-to-refresh). 
```
JS: =Debug===============
JS: 2016-05-23T23:19:51.117Z: Pan centerContent delta: [-4.6382293701171875, 0.6852951049804688] state: 2
JS: ======================
JS: =Debug===============
JS: 2016-05-23T23:19:51.134Z: Pan centerContent delta: [-7.109344482421875, 1.5095863342285156] state: 2
JS: ======================
JS: =Debug===============
JS: 2016-05-23T23:19:51.150Z: Pan centerContent delta: [-9.58441162109375, 1.5095863342285156] state: 2
JS: ======================
JS: =Debug===============
JS: 2016-05-23T23:19:51.167Z: Pan centerContent delta: [-9.58441162109375, 1.5095863342285156] state: 3
```

On the elements representing aside left I can get them as well.  
```
JS: =Debug===============
JS: 2016-05-23T23:27:09.866Z: Pan asideLeft delta: [67.61468505859375, 7.176422119140625] state: 2
JS: ======================
JS: =Debug===============
JS: 2016-05-23T23:27:09.886Z: Pan asideLeft delta: [65.71446228027344, 5.87274169921875] state: 2
JS: ======================
JS: =Debug===============
JS: 2016-05-23T23:27:09.909Z: Pan asideLeft delta: [65.71446228027344, 5.87274169921875] state: 3
JS: ======================
```

But panning on any content in the pull-to-refresh there is a deathly silence, except for the wiggling of the pull to refresh. Any ideas?

**Comment by bradmartin** [comment]
Not entirely certain, but I want to say that's part (kinda a crappy part) of using the android PullRefreshLayout. If you download the IGN app, that have a slider on the main page using the PullRefreshLayout and sometimes it's a pain to swipe the image slider because of the refresh layout. So I think it's just how that is, there might be some way to get into the gestures on the items and do some hacking but I don't know where to start right now.

**Comment by matt4446** [comment]
I could take a look. I feel like it could be time for me to take a trip into the native side this evening. 
If It won't bubble then there is always the possibility of subscribing to something that knows the pan events...   
```
public class SwipeRefreshLayout 
extends ViewGroup implements NestedScrollingParent, NestedScrollingChild
```
One of those must know. I will see I guess.

**Comment by bradmartin** [comment]
Yea that's the layout I meant :) I kept using the pullrefreshlayout which
is nothing lol sorry about that :smile:

**Comment by matt4446** [comment]
I hadnt noticed your mistake.
I still plan to look at that file 'SwipeRefreshLayout' at some point ... 
But I decided to make a sample project (https://github.com/matt4446/Demo-Material-NativeScript/tree/master/screenshots/Android) for your material items with ns + angular in the meantime. It seemed relevant seeing there are a lot of questions around it. I have not got around to the fab yet. 
I'll probably use this to test the pan events.

**Comment by bradmartin** [comment]
Can we close this @matt4446 ? Just let me know :smile:

**Comment by matt4446** [comment]
@bradmartin We might as well. I have not got around to trying it out yet. I'll attempt it again some point! 

*dreams for the day I can use work time to solve these problems*
